### ISSUE TITLE
Short-Keys to control recording can't be changed

### ISSUE THREAD

**Issue by MerlinCooper** [MerlinCooper/iRacingReplayDirector#52]
- Currently short-keys are for STOP/START (ALT+F9) and PAUSE/RESUME (ALT+F10) are not changeable.
- Configuration Dialog does not contain any information what short-key is being used for pause/resume when using Fast-Video-Recording option

**Comment by MerlinCooper** [comment]
Reopen branch to implement possibility to change hot-keys.

/cib

**Comment by mrzoops** [comment]
In the latest branch I see the added info in the config for pause/unpause replay but its showing as F9 instead of F10.

**Comment by MerlinCooper** [comment]
> 
> 
> In the latest branch I see the added info in the config for pause/unpause replay but its showing as F9 instead of F10.

Thanks for providing feedback. Did just not set the text correctly in the previous version. Keystroke sent was already ALT+F10 tho. Fixed that with release [20201220.3](https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20201220.3)
![image](https://user-images.githubusercontent.com/3088879/102723491-91368200-4308-11eb-9a50-90130a55f8df.png)

**Comment by MerlinCooper** [comment]
Will implement the feature to allow configuration of hotkeys used to control video recording software only in the Advanced Settings Dialog.

**Comment by MerlinCooper** [comment]
Create branch for that purpose
/cib

**Comment by MerlinCooper** [comment]
@mrzoops Spent some time on how hotkeys being sent and allow to make them configurable. Mainly because the way hotkeys were sent could contribute (not being the only root-cause) to the stuttering issue when using Fast-Recording. 

Would appreciate if you could test the pre-released version as well and provide feedback. 

https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20220528.1

**Comment by mrzoops** [comment]
> Would appreciate if you could test the pre-released version as well and provide feedback.

I tried testing today. When trying to set the ALT-F2 in the advanced options, I get an error immediately when opening the "Use New Settings Dialog (alpha)" It then opens normally but I cannot successfully set ALT-F2. I can change the start stop buttons, but not the pause/resume. It just doesn't accept any key commands. 

EDIT: I also tried  manually editing the settings file but it doesn't take it either. 

Error from logs: 

Waiting to connect to iRacing application
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.AdvanceGeneralSettingsDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.btTestPauseResumeHotKey_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.AdvanceGeneralSettingsDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.AdvanceGeneralSettingsDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.AdvanceGeneralSettingsDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Waiting to connect to iRacing application
Must specify valid information for parsing in the string.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.AdvancedGeneralSettingsDlg.AdvanceGeneralSettingsDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mrzoops** [comment]
Ok I managed to manually get it into the settings by editing the iracing-replay-director.settings file.

**Comment by mrzoops** [comment]
Still stuttering between camera switches when I have tested twice. Also, not getting overlays with fast encode.

**Comment by MerlinCooper** [comment]
> Still stuttering between camera switches when I have tested twice. Also, not getting overlays with fast encode.

Thanks for the feedback. Stuttering as mentioned will still take some time - multiple issues are contributing there. Thus no easy fix.

With regard to the overlays in fast recording mode you will have to use an third party overlay. The way it‘s done in the original application is analyze, capture, encode is very time consuming. The overlays are done during the encode phase - that‘s the one I‘m trying to eliminate.

**Comment by MerlinCooper** [comment]
> Ok I managed to manually get it into the settings by editing the iracing-replay-director.settings file.

@mrzoops 
Can't really reproduce the issue - seems to work o.k. (see video).
https://user-images.githubusercontent.com/3088879/170859426-7be6d7c1-2bd5-4e36-a80e-99324b0f69f4.mp4

Could you please rename your settings file - the application should then generate a new settings file with default values. If it still failes a short video showing the issue would be appreciated.

**Comment by mrzoops** [comment]
> > Ok I managed to manually get it into the settings by editing the iracing-replay-director.settings file.
> 
> @mrzoops Can't really reproduce the issue - seems to work o.k. (see video). https://user-images.githubusercontent.com/3088879/170859426-7be6d7c1-2bd5-4e36-a80e-99324b0f69f4.mp4
> 
> Could you please rename your settings file - the application should then generate a new settings file with default values. If it still failes a short video showing the issue would be appreciated.

Deleting and recreating the settings file fixed it. Thank you.
