### ISSUE TITLE
Overlay / Transcoding Help 

### ISSUE THREAD

**Issue by ccarroll824** [MerlinCooper/iRacingReplayDirector#76]
On version, 0606.1, I keep receiving error messages when transcoding the video. I'm not much for coding so I don't understand the issue. Can anyone give me some guidance on how to resolve the issue? Everything has worked fine up until this point.

ERROR: Could not load file or assembly 'NoOverlay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
ERROR:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at iRacingReplayDirector.PluginProxy..ctor(String pluginName)
   at iRacingReplayDirector.Phases.Transcoding.LeaderBoard.set_PluginName(String value)
   at iRacingReplayDirector.Phases.TranscodeAndOverlay.Apply(String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, Func`1 isAborted, String pluginName)
Could not load file or assembly 'NoOverlay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
   at iRacingReplayDirector.Phases.TranscodeAndOverlay.Apply(String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, Func`1 isAborted, String pluginName)
   at iRacingReplayDirector.Phases.TranscodeAndOverlayArguments.Apply()
   at iRacingReplayDirector.Phases.TranscodeAndOverlayArguments.Apply()
   at iRacingReplayDirector.Phases.TranscodeAndOverlayMarshaled.Apply(String name, String gameDataFile, Int32 videoBitRate, String destFile, Boolean highlights, Action`2 progressReporter, CancellationToken token)
One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at iRacingReplayDirector.Phases.IRacingReplay._OverlayRaceDataOntoVideo(Action`2 progress, Action completed, Boolean highlightOnly, Boolean bShutdownAfterCompleted, CancellationToken token)
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass51_0.<OverlayRaceDataOntoVideo>b__0()
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass58_0.<InTheBackground>b__0()
Process aborted

**Comment by MerlinCooper** [comment]
Am I right that you try to transcode without an overlay? Or what does the setting in the "Configure Video Capture" Dialog look like? If you want no overlay the last line should look like this.
![grafik](https://user-images.githubusercontent.com/3088879/214780718-dc7d70dd-917a-42a1-8be7-ff2ae907a3c9.png)

Furthermore in your PlugIn Subfolder there needs to be a directory named "NoOverlay" and it's supposed to contain multiple files. Can you post what's in your Plugin/NoOverlay Subfolder?

**Comment by MerlinCooper** [comment]
@ccarroll824 eill need more information to have a look. Will close the issue with for the moment, if you provide more information we can re-open the topic
