### ISSUE TITLE
Misleading UI to set Hotkey causes Error: Must specify valid information for parsing in the string. 

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#78]
Version 1.2.8192.103
Running the Short Test Only with Fast-Video-Recording (alpha)
Log attached.

2022-10-27T13:55:12	INFO: Sending key event to pause/resume recording 
2022-10-27T13:55:12	ERROR: Must specify valid information for parsing in the string.
2022-10-27T13:55:12	ERROR:    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WK.Libraries.HotkeyListenerNS.HotkeyListener.Convert(String hotkey)
   at WK.Libraries.HotkeyListenerNS.Hotkey..ctor(String hotkey)
   at iRacingReplayDirector.Phases.Direction.VideoCapture.SendKeyStroke_PauseResume()
   at iRacingReplayDirector.Phases.Direction.VideoCapture.Pause()
   at iRacingReplayDirector.Phases.Direction.VideoCapture.Deactivate(Boolean bRecordUsingPauseResume)
   at iRacingReplayDirector.Phases.IRacingReplay._CaptureOpeningScenes(Action onComplete)
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass40_0.<Add>b__0()
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass58_0.<InTheBackground>b__0()
2022-10-27T13:55:12	INFO: Process aborted
[capture.log](https://github.com/MerlinCooper/iRacingReplayDirector/files/9882424/capture.log)

**Comment by MerlinCooper** [comment]
You need to provide a littel bit more information to support an analysis. What did you do before the failure occured?

**Comment by SoOlditHurts** [comment]
Sorry, I'll start providing more details. Basically, I get this whenever I try the "Fast Video Recording" mode instead of having it unchecked. If unchecked, it works for me everytime. If checked, it never works. I'll do some more testing with this feature today and see if I can narrow anything down.

**Comment by SoOlditHurts** [comment]
My steps to replicate:

1. Start Replay Director
2. Check the Short Test Only checkbox. Leave Fast-Video-Recording (alpha) on.
3. Start OBS Studio
4. Start an iRacing Replay. Press space to remove the overlay.
5. Press Begin Capture in Replay Directory
6. It analysis the replay just fine
7. It then moves to "capturing..." and the screen moves between several scenes in iRacing. 
8. OBS starts recording and the replay starts playing in iRacing.
9. Replay Director immediately posts a message that there was an error. I included the error above.
10. If I uncheck "Fast-Video-Recording (alpha)", check "Encode Video After Capture" and do the Begin Capture, it will go from start to finish without issue.

**Comment by MerlinCooper** [comment]
Thanks for the information. Did a quick test to reproduce the issue - on my side it did not crash. But this oombination hasn't tested before. For my own testing I do use a shorter replay file and mostly I am only testing/using the "Fast-Video-Recording". 

The error message though indicated that something is going wrong with the hotkeys used to pause/resume OBS. Could you verify whether pause/resume is configured properly by 

- Select "use new settings dialog"
- click on "Configure General"
- got to "hot keys" tab
- configure the hotkeys as they are set in OBS
- have OBS running and use the send buttons to start, pause/resume and stop OBS. 

![grafik](https://user-images.githubusercontent.com/3088879/215027676-1fb00882-064c-4563-b9cb-b327d88a1c49.png)

**Comment by SoOlditHurts** [comment]
Added the hotkey. It confused me. I figured it would be a mapping type config where I press Alt+F10 and it takes it. I discovered I could instead type in the phrase Alt + F10 and that worked. 

Fast-Video-Recording (alpha) now functions without errors in the process. However...

I then did a test using the 20230127.1 version you sent me and while it did complete the Capture, the resulting replayscript comes back with “Error reading the video file. Sequence contains no elements.” I noticed the “VideoFiles” value in the json is “null”. This happened both with the Short Test both Off and On. Tested it both ways.

The .mp4 file(s) do exist.

**Comment by MerlinCooper** [comment]
Thanks for the feedback - will keep this issue open and might have a look sometimes how to improve the UI (#SoonINIracing 😂)

For your other observation I would appreciate if you could create another issue and provide more details, e.g. the created files including the mp4.

as mentioned in the application ‚FastVideoRecording‘ is alpha and there is a long way to go until I will be happy with it to call it a beta version.
